In [ ]:
#Name: Swaraj Suresh Shinde
#PRN: 125B1D053
#Batch: A3
#Assignment 3b

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#load dataset
df=pd.read_csv("asg3b-dataset")

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 198577 entries, 0 to 198576
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   Season   198577 non-null  int64
 1   DayNum   198577 non-null  int64
 2   WTeamID  198577 non-null  int64
 3   WScore   198577 non-null  int64
 4   LTeamID  198577 non-null  int64
 5   LScore   198577 non-null  int64
 6   WLoc     198577 non-null  str
 7   NumOT    198577 non-null  int64
dtypes: int64(7), str(1)
memory usage: 12.3 MB

In [ ]:
#1.display all object columns
#columns storing string or text are object columns
#they have dtype as object or string

for col in df.columns:
    if df[col].dtype=='str' or df[col].dtype=='object':
        print(col)

WLoc

In [14]:
#2.Find all games where winning team scored more than 150 points
df[df['WScore']>150]

       Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
5269     1986      75     1258     151     1109     107    H      0
12046    1988      40     1328     152     1147      84    H      0
12355    1988      52     1328     151     1173      99    N      0
16040    1989      40     1328     152     1331     122    H      0
16853    1989      68     1258     162     1109     144    A      0
17867    1989      92     1258     181     1109     150    H      0
19653    1990      30     1328     173     1109     101    H      0
19971    1990      38     1258     152     1109     137    A      0
20022    1990      40     1116     166     1109     101    H      0
22145    1990      97     1258     157     1362     115    H      0
23582    1991      26     1318     152     1258     123    N      0
24341    1991      47     1328     172     1258     112    H      0
24970    1991      68     1258     186     1109     140    H      0
25656    1991      84     1106     151     1212      97    H      0
28687    1992      54     1261     159     1319      86    H      0
35023    1993     112     1380     155     1341      91    A      0
40060    1995      32     1375     156     1341     114    H      0
52600    1998      33     1395     153     1410      87    H      0

In [17]:
#3.Winning team score>150 and losing team score<100
df[(df['WScore']>150) & (df['LScore']<100)]

       Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
12046    1988      40     1328     152     1147      84    H      0
12355    1988      52     1328     151     1173      99    N      0
25656    1991      84     1106     151     1212      97    H      0
28687    1992      54     1261     159     1319      86    H      0
35023    1993     112     1380     155     1341      91    A      0
52600    1998      33     1395     153     1410      87    H      0

In [ ]:
#4.no of games played per season
df['Season'].value_counts()
#it sorts largest value first

Season
2026    5647
2025    5641
2024    5607
2023    5602
2019    5463
2018    5405
2017    5395
2016    5369
2014    5362
2015    5354
2022    5345
2020    5328
2013    5320
2010    5263
2012    5253
2009    5249
2011    5246
2008    5163
2007    5043
2006    4757
2005    4675
2003    4616
2004    4571
2002    4555
2000    4519
2001    4467
1999    4222
1998    4167
1997    4155
1992    4127
1991    4123
1996    4122
1995    4077
1994    4060
1990    4045
1989    4037
1993    3982
1988    3955
1987    3915
2021    3855
1986    3783
1985    3737
Name: count, dtype: int64

In [22]:
df['Season'].value_counts().sort_index()

Season
1985    3737
1986    3783
1987    3915
1988    3955
1989    4037
1990    4045
1991    4123
1992    4127
1993    3982
1994    4060
1995    4077
1996    4122
1997    4155
1998    4167
1999    4222
2000    4519
2001    4467
2002    4555
2003    4616
2004    4571
2005    4675
2006    4757
2007    5043
2008    5163
2009    5249
2010    5263
2011    5246
2012    5253
2013    5320
2014    5362
2015    5354
2016    5369
2017    5395
2018    5405
2019    5463
2020    5328
2021    3855
2022    5345
2023    5602
2024    5607
2025    5641
2026    5647
Name: count, dtype: int64

In [27]:
#5.avg winning score of each team
df.groupby('WTeamID')['WScore'].mean()

WTeamID
1101    76.576687
1102    71.042607
1103    76.849239
1104    78.377129
1105    74.423077
          ...
1477    74.194444
1478    77.515152
1479    74.555556
1480    82.055556
1481    69.545455
Name: WScore, Length: 381, dtype: float64

In [32]:
#6.How many games were won at home, away, and at neutral locations
df['WLoc'].value_counts()

WLoc
H    117154
A     61033
N     20390
Name: count, dtype: int64