In [ ]:
#Name: Swaraj Suresh Shinde
#PRN: 125B1D053
#Batch: A3
#Assignment 2a

In [1]:
import pandas as pd
import sqlite3 #module used to create,connect db

In [2]:
txt_data = pd.read_table("sample-txt-files-sample3.txt")
print(txt_data)

                         Quod equidem non reprehendo;
0   Lorem ipsum dolor sit amet, consectetur adipis...
1   Iam id ipsum absurdum, maximum malum neglegi. ...
2                           Quis istum dolorem timet?
3   Summus dolor plures dies manere non potest? Di...
4   Ex eorum enim scriptis et institutis cum omnis...
5   Quod si ita est, sequitur id ipsum, quod te ve...
6   Quem si tenueris, non modo meum Ciceronem, sed...
7   Stulti autem malorum memoria torquentur, sapie...
8   Esse enim quam vellet iniquus iustus poterat i...
9   Quae autem natura suae primae institutionis ob...
10  Verum tamen cum de rebus grandioribus dicas, i...
11  Hoc est non modo cor non habere, sed ne palatu...
12  Voluptatem cum summum bonum diceret, primum in...
13                              Idemne, quod iucunde?
14  Haec mihi videtur delicatior, ut ita dicam, mo...

In [3]:
json_data = pd.read_json("students.json")
json_data #in jupyter if last line is variable then it automatically prints

                                            students
0  {'id': '001', 'firstName': 'Bhavik', 'lastName...
1  {'id': '002', 'firstName': 'Bharat', 'lastName...
2  {'id': '003', 'firstName': 'Arvind', 'lastName...
3  {'id': '002', 'firstName': 'Amit', 'lastName':...

In [7]:
json_data = pd.read_json("students.json")
json_df = pd.json_normalize(json_data["students"])
json_df

,id,firstName,lastName,fullName,fatherName,grades,age,class
0,001,Bhavik,Taneja,Bhavik Taneja,Mr. Dinesh Taneja,"[2.3, 4.3, 5]",15,10
1,002,Bharat,Badera,Bharat Badera,Mr. RadheShyam Badera,"[2.1, 4.6, 5]",14,9
2,003,Arvind,Gaur,Arvind Gaur,Mr. L. S. Gaur,"[2.5, 3.3, 4]",18,12
3,002,Amit,Tek,Amit Tek,Mr. A.K. Tek,"[2, 4, 4]",18,12

In [10]:
print(json_df)

    id firstName lastName       fullName             fatherName  \
0  001    Bhavik   Taneja  Bhavik Taneja      Mr. Dinesh Taneja
1  002    Bharat   Badera  Bharat Badera  Mr. RadheShyam Badera
2  003    Arvind     Gaur    Arvind Gaur         Mr. L. S. Gaur
3  002      Amit      Tek       Amit Tek           Mr. A.K. Tek

          grades  age class
0  [2.3, 4.3, 5]   15    10
1  [2.1, 4.6, 5]   14     9
2  [2.5, 3.3, 4]   18    12
3      [2, 4, 4]   18    12

In [11]:
print(json_df.head())

    id firstName lastName       fullName             fatherName  \
0  001    Bhavik   Taneja  Bhavik Taneja      Mr. Dinesh Taneja
1  002    Bharat   Badera  Bharat Badera  Mr. RadheShyam Badera
2  003    Arvind     Gaur    Arvind Gaur         Mr. L. S. Gaur
3  002      Amit      Tek       Amit Tek           Mr. A.K. Tek

          grades  age class
0  [2.3, 4.3, 5]   15    10
1  [2.1, 4.6, 5]   14     9
2  [2.5, 3.3, 4]   18    12
3      [2, 4, 4]   18    12

In [12]:
print(json_df.tail())

    id firstName lastName       fullName             fatherName  \
0  001    Bhavik   Taneja  Bhavik Taneja      Mr. Dinesh Taneja
1  002    Bharat   Badera  Bharat Badera  Mr. RadheShyam Badera
2  003    Arvind     Gaur    Arvind Gaur         Mr. L. S. Gaur
3  002      Amit      Tek       Amit Tek           Mr. A.K. Tek

          grades  age class
0  [2.3, 4.3, 5]   15    10
1  [2.1, 4.6, 5]   14     9
2  [2.5, 3.3, 4]   18    12
3      [2, 4, 4]   18    12

In [13]:
print(json_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          4 non-null      str
 1   firstName   4 non-null      str
 2   lastName    4 non-null      str
 3   fullName    4 non-null      str
 4   fatherName  4 non-null      str
 5   grades      4 non-null      object
 6   age         4 non-null      int64
 7   class       4 non-null      str
dtypes: int64(1), object(1), str(6)
memory usage: 557.0+ bytes
None

In [14]:
print(json_df.describe(include='all'))

         id firstName lastName       fullName         fatherName  \
count     4         4        4              4                  4
unique    3         4        4              4                  4
top     002    Bhavik   Taneja  Bhavik Taneja  Mr. Dinesh Taneja
freq      2         1        1              1                  1
mean    NaN       NaN      NaN            NaN                NaN
std     NaN       NaN      NaN            NaN                NaN
min     NaN       NaN      NaN            NaN                NaN
25%     NaN       NaN      NaN            NaN                NaN
50%     NaN       NaN      NaN            NaN                NaN
75%     NaN       NaN      NaN            NaN                NaN
max     NaN       NaN      NaN            NaN                NaN

               grades        age class
count               4   4.000000     4
unique              4        NaN     3
top     [2.3, 4.3, 5]        NaN    12
freq                1        NaN     2
mean              NaN  16.250000   NaN
std               NaN   2.061553   NaN
min               NaN  14.000000   NaN
25%               NaN  14.750000   NaN
50%               NaN  16.500000   NaN
75%               NaN  18.000000   NaN
max               NaN  18.000000   NaN

In [15]:
print(json_df.dtypes)

id               str
firstName        str
lastName         str
fullName         str
fatherName       str
grades        object
age            int64
class            str
dtype: object

In [16]:
print(json_df.shape)

(4, 8)

In [21]:
from sklearn.datasets import load_iris
import pandas as pd;
iris = load_iris()
print(type(iris.data))
print(iris.data[:3])
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target

<class 'numpy.ndarray'>
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]

In [31]:
csv_data = pd.read_csv("iris.csv")
csv_data

,Unnamed: 0,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,0,5.1,3.5,1.4,0.2
1,1,4.9,3.0,1.4,0.2
2,2,4.7,3.2,1.3,0.2
3,3,4.6,3.1,1.5,0.2
4,4,5.0,3.6,1.4,0.2
...,...,...,...,...,...
145,145,6.7,3.0,5.2,2.3
146,146,6.3,2.5,5.0,1.9
147,147,6.5,3.0,5.2,2.0
148,148,6.2,3.4,5.4,2.3
149,149,5.9,3.0,5.1,1.8

In [30]:
csv_data.head()

,Unnamed: 0,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,0,5.1,3.5,1.4,0.2
1,1,4.9,3.0,1.4,0.2
2,2,4.7,3.2,1.3,0.2
3,3,4.6,3.1,1.5,0.2
4,4,5.0,3.6,1.4,0.2

In [32]:
csv_data.tail()

,Unnamed: 0,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
145,145,6.7,3.0,5.2,2.3
146,146,6.3,2.5,5.0,1.9
147,147,6.5,3.0,5.2,2.0
148,148,6.2,3.4,5.4,2.3
149,149,5.9,3.0,5.1,1.8

In [33]:
csv_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         150 non-null    int64
 1   sepal length (cm)  149 non-null    float64
 2   sepal width (cm)   149 non-null    float64
 3   petal length (cm)  149 non-null    float64
 4   petal width (cm)   150 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

In [26]:
csv_data.describe()

,Unnamed: 0,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,149.000000,149.000000,149.000000,150.000000
mean,74.500000,5.850336,3.055705,3.773826,1.283333
std,43.445368,0.826391,0.436878,1.760543,1.293578
min,0.000000,4.300000,2.000000,1.000000,0.100000
25%,37.250000,5.100000,2.800000,1.600000,0.300000
50%,74.500000,5.800000,3.000000,4.400000,1.300000
75%,111.750000,6.400000,3.300000,5.100000,1.800000
max,149.000000,7.900000,4.400000,6.900000,14.000000

In [34]:
csv_data.dtypes

Unnamed: 0             int64
sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
dtype: object

In [37]:
csv_data.shape

(150, 5)

In [39]:
import sqlite3
conn = sqlite3.connect("student.db")
cursor = conn.cursor()
cursor.execute("""
CREATE TABLE IF NOT EXISTS Students2 (
    ID INTEGER,
    Name TEXT,
    Age INTEGER,
    Marks INTEGER
)
""")
cursor.execute("INSERT INTO Students2 VALUES (1, 'Bhavik', 20, 85)")
cursor.execute("INSERT INTO Students2 VALUES (2, 'Bharat', 21, 90)")
cursor.execute("INSERT INTO Students2 VALUES (3, 'Arvind', 22, 88)")
cursor.execute("INSERT INTO Students2 VALUES (4, 'Amit', 20, 92)")
conn.commit()

In [40]:
df = pd.read_sql_query("SELECT * FROM Students2",conn)
print("Head: ")
print(df.head())

Head:
   ID    Name  Age  Marks
0   1  Bhavik   20     85
1   2  Bharat   21     90
2   3  Arvind   22     88
3   4    Amit   20     92

In [41]:
print(df.tail())
print(df.info())
print(df.describe())
print(df.dtypes)
print(df.shape)
print(df.columns)
conn.close()

   ID    Name  Age  Marks
0   1  Bhavik   20     85
1   2  Bharat   21     90
2   3  Arvind   22     88
3   4    Amit   20     92
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      4 non-null      int64
 1   Name    4 non-null      str
 2   Age     4 non-null      int64
 3   Marks   4 non-null      int64
dtypes: int64(3), str(1)
memory usage: 282.0 bytes
None
             ID        Age      Marks
count  4.000000   4.000000   4.000000
mean   2.500000  20.750000  88.750000
std    1.290994   0.957427   2.986079
min    1.000000  20.000000  85.000000
25%    1.750000  20.000000  87.250000
50%    2.500000  20.500000  89.000000
75%    3.250000  21.250000  90.500000
max    4.000000  22.000000  92.000000
ID       int64
Name       str
Age      int64
Marks    int64
dtype: object
(4, 4)
Index(['ID', 'Name', 'Age', 'Marks'], dtype='str')

In [43]:
conn = sqlite3.connect("student.db")
query = "SELECT * FROM student"
df = pd.read_sql_query(query, conn)
print(df)

    NAME             CLASS SECTION  MARKS
0   AMIT      Data Science       C     98
1    RAM     Data Analytic       A     92
2  SUMIT  Computer Science       B     96
3   AMAN                AI       A     88
4  KAMAl             GENAI       C     68
5  ANSHU                ML       B     99