In [2]:
import pandas as pd
df=pd.read_csv("cbb.csv")

In [3]:
#1.display samplle records using head and tail
print(df.head())
print(df.tail())

             TEAM CONF   G   W  ADJOE  ADJDE  BARTHAG  EFG_O  EFG_D   TOR  \
0  North Carolina  ACC  40  33  123.3   94.9   0.9531   52.6   48.1  15.4
1       Wisconsin  B10  40  36  129.1   93.6   0.9758   54.8   47.7  12.4
2        Michigan  B10  40  33  114.4   90.4   0.9375   53.9   47.7  14.0
3      Texas Tech  B12  38  31  115.2   85.2   0.9696   53.5   43.0  17.7
4         Gonzaga  WCC  39  37  117.8   86.3   0.9728   56.6   41.1  16.2

   ...  FTRD  2P_O  2P_D  3P_O  3P_D  ADJ_T   WAB  POSTSEASON  SEED  YEAR
0  ...  30.4  53.9  44.6  32.7  36.2   71.7   8.6         2ND   1.0  2016
1  ...  22.4  54.8  44.7  36.5  37.5   59.3  11.3         2ND   1.0  2015
2  ...  30.0  54.7  46.8  35.2  33.2   65.9   6.9         2ND   3.0  2018
3  ...  36.6  52.8  41.9  36.5  29.7   67.5   7.0         2ND   3.0  2019
4  ...  26.9  56.3  40.0  38.2  29.0   71.5   7.7         2ND   1.0  2017

[5 rows x 24 columns]
                        TEAM  CONF   G  W  ADJOE  ADJDE  BARTHAG  EFG_O  \
4244             The Citadel    SC  30  5   94.0  117.6   0.0705   46.9
4245             Chicago St.   NEC  32  4   92.8  116.4   0.0688   44.4
4246     Arkansas Pine Bluff  SWAC  31  6   95.3  121.8   0.0563   50.3
4247              Coppin St.  MEAC  30  6   88.0  112.6   0.0556   44.0
4248  Mississippi Valley St.  SWAC  31  3   83.1  125.3   0.0088   42.1

      EFG_D   TOR  ...  FTRD  2P_O  2P_D  3P_O  3P_D  ADJ_T   WAB  POSTSEASON  \
4244   54.5  19.5  ...  32.8  49.5  56.3  29.2  34.7   64.8 -21.4         NaN
4245   54.9  18.5  ...  36.9  43.4  55.7  30.6  35.8   68.8 -21.7         NaN
4246   56.3  20.4  ...  40.5  52.6  58.5  31.0  35.7   71.8 -20.0         NaN
4247   55.6  21.6  ...  37.1  44.2  56.3  29.0  36.3   68.2 -19.0         NaN
4248   57.9  24.3  ...  38.4  41.6  58.8  28.8  37.7   65.1 -21.0         NaN

      SEED  YEAR
4244   NaN  2025
4245   NaN  2025
4246   NaN  2025
4247   NaN  2025
4248   NaN  2025

[5 rows x 24 columns]

In [6]:
#2.Display number of records in dataset
print(df.shape)
print(len(df))

(4249, 24)
4249

In [5]:
#3.Display the number of missing values in each column
print(df.isnull().sum())

TEAM             0
CONF             0
G                0
W                0
ADJOE            0
ADJDE            0
BARTHAG          0
EFG_O            0
EFG_D            0
TOR              0
TORD             0
ORB              0
DRB              0
FTR              0
FTRD             0
2P_O             0
2P_D             0
3P_O             0
3P_D             0
ADJ_T            0
WAB              0
POSTSEASON    3433
SEED          3433
YEAR             0
dtype: int64

In [8]:
#4.Display maximum value present in each column
print(df.max(numeric_only=True))

G            40.0000
W            38.0000
ADJOE       130.6000
ADJDE       125.3000
BARTHAG       0.9842
EFG_O        61.0000
EFG_D        60.1000
TOR          27.1000
TORD         28.5000
ORB          43.6000
DRB          40.4000
FTR          58.6000
FTRD         60.7000
2P_O         64.0000
2P_D         61.2000
3P_O         44.1000
3P_D         43.1000
ADJ_T        83.4000
WAB          13.1000
SEED         16.0000
YEAR       2025.0000
dtype: float64

In [11]:
#5.Display unique calues present in each column
for col in df.columns:
    print(f"\ncolumn: {col}")
    print(df[col].unique)

column: TEAM
<bound method Series.unique of 0               North Carolina
1                    Wisconsin
2                     Michigan
3                   Texas Tech
4                      Gonzaga
                 ...
4244               The Citadel
4245               Chicago St.
4246       Arkansas Pine Bluff
4247                Coppin St.
4248    Mississippi Valley St.
Name: TEAM, Length: 4249, dtype: str>

column: CONF
<bound method Series.unique of 0        ACC
1        B10
2        B10
3        B12
4        WCC
        ...
4244      SC
4245     NEC
4246    SWAC
4247    MEAC
4248    SWAC
Name: CONF, Length: 4249, dtype: str>

column: G
<bound method Series.unique of 0       40
1       40
2       40
3       38
4       39
        ..
4244    30
4245    32
4246    31
4247    30
4248    31
Name: G, Length: 4249, dtype: int64>

column: W
<bound method Series.unique of 0       33
1       36
2       33
3       31
4       37
        ..
4244     5
4245     4
4246     6
4247     6
4248     3
Name: W, Length: 4249, dtype: int64>

column: ADJOE
<bound method Series.unique of 0       123.3
1       129.1
2       114.4
3       115.2
4       117.8
        ...
4244     94.0
4245     92.8
4246     95.3
4247     88.0
4248     83.1
Name: ADJOE, Length: 4249, dtype: float64>

column: ADJDE
<bound method Series.unique of 0        94.9
1        93.6
2        90.4
3        85.2
4        86.3
        ...
4244    117.6
4245    116.4
4246    121.8
4247    112.6
4248    125.3
Name: ADJDE, Length: 4249, dtype: float64>

column: BARTHAG
<bound method Series.unique of 0       0.9531
1       0.9758
2       0.9375
3       0.9696
4       0.9728
         ...
4244    0.0705
4245    0.0688
4246    0.0563
4247    0.0556
4248    0.0088
Name: BARTHAG, Length: 4249, dtype: float64>

column: EFG_O
<bound method Series.unique of 0       52.6
1       54.8
2       53.9
3       53.5
4       56.6
        ...
4244    46.9
4245    44.4
4246    50.3
4247    44.0
4248    42.1
Name: EFG_O, Length: 4249, dtype: float64>

column: EFG_D
<bound method Series.unique of 0       48.1
1       47.7
2       47.7
3       43.0
4       41.1
        ...
4244    54.5
4245    54.9
4246    56.3
4247    55.6
4248    57.9
Name: EFG_D, Length: 4249, dtype: float64>

column: TOR
<bound method Series.unique of 0       15.4
1       12.4
2       14.0
3       17.7
4       16.2
        ...
4244    19.5
4245    18.5
4246    20.4
4247    21.6
4248    24.3
Name: TOR, Length: 4249, dtype: float64>

column: TORD
<bound method Series.unique of 0       18.2
1       15.8
2       19.5
3       22.8
4       17.1
        ...
4244    15.2
4245    18.2
4246    16.8
4247    20.5
4248    15.0
Name: TORD, Length: 4249, dtype: float64>

column: ORB
<bound method Series.unique of 0       40.7
1       32.1
2       25.5
3       27.4
4       30.0
        ...
4244    27.2
4245    22.6
4246    26.3
4247    26.5
4248    22.7
Name: ORB, Length: 4249, dtype: float64>

column: DRB
<bound method Series.unique of 0       30.0
1       23.7
2       24.9
3       28.7
4       26.2
        ...
4244    32.0
4245    33.6
4246    34.6
4247    33.9
4248    38.0
Name: DRB, Length: 4249, dtype: float64>

column: FTR
<bound method Series.unique of 0       32.3
1       36.2
2       30.7
3       32.9
4       39.0
        ...
4244    32.8
4245    26.8
4246    32.8
4247    36.4
4248    30.3
Name: FTR, Length: 4249, dtype: float64>

column: FTRD
<bound method Series.unique of 0       30.4
1       22.4
2       30.0
3       36.6
4       26.9
        ...
4244    32.8
4245    36.9
4246    40.5
4247    37.1
4248    38.4
Name: FTRD, Length: 4249, dtype: float64>

column: 2P_O
<bound method Series.unique of 0       53.9
1       54.8
2       54.7
3       52.8
4       56.3
        ...
4244    49.5
4245    43.4
4246    52.6
4247    44.2
4248    41.6
Name: 2P_O, Length: 4249, dtype: float64>

column: 2P_D
<bound method Series.unique of 0       44.6
1       44.7
2       46.8
3       41.9
4       40.0
        ...
4244    56.3
4245    55.7
4246    58.5
4247    56.3
4248    58.8
Name: 2P_D, Length: 4249, dtype: float64>

column: 3P_O
<bound method Series.unique of 0       32.7
1       36.5
2       35.2
3       36.5
4       38.2
        ...
4244    29.2
4245    30.6
4246    31.0
4247    29.0
4248    28.8
Name: 3P_O, Length: 4249, dtype: float64>

column: 3P_D
<bound method Series.unique of 0       36.2
1       37.5
2       33.2
3       29.7
4       29.0
        ...
4244    34.7
4245    35.8
4246    35.7
4247    36.3
4248    37.7
Name: 3P_D, Length: 4249, dtype: float64>

column: ADJ_T
<bound method Series.unique of 0       71.7
1       59.3
2       65.9
3       67.5
4       71.5
        ...
4244    64.8
4245    68.8
4246    71.8
4247    68.2
4248    65.1
Name: ADJ_T, Length: 4249, dtype: float64>

column: WAB
<bound method Series.unique of 0        8.6
1       11.3
2        6.9
3        7.0
4        7.7
        ...
4244   -21.4
4245   -21.7
4246   -20.0
4247   -19.0
4248   -21.0
Name: WAB, Length: 4249, dtype: float64>

column: POSTSEASON
<bound method Series.unique of 0       2ND
1       2ND
2       2ND
3       2ND
4       2ND
       ...
4244    NaN
4245    NaN
4246    NaN
4247    NaN
4248    NaN
Name: POSTSEASON, Length: 4249, dtype: str>

column: SEED
<bound method Series.unique of 0       1.0
1       1.0
2       3.0
3       3.0
4       1.0
       ...
4244    NaN
4245    NaN
4246    NaN
4247    NaN
4248    NaN
Name: SEED, Length: 4249, dtype: float64>

column: YEAR
<bound method Series.unique of 0       2016
1       2015
2       2018
3       2019
4       2017
        ...
4244    2025
4245    2025
4246    2025
4247    2025
4248    2025
Name: YEAR, Length: 4249, dtype: int64>

In [12]:
#6.Display number of unique values present in each column
print(df.nunique())

TEAM           380
CONF            35
G               32
W               39
ADJOE          401
ADJDE          347
BARTHAG       3398
EFG_O          189
EFG_D          170
TOR            136
TORD           150
ORB            238
DRB            188
FTR            299
FTRD           339
2P_O           213
2P_D           195
3P_O           167
3P_D           147
ADJ_T          188
WAB            364
POSTSEASON       8
SEED            16
YEAR            12
dtype: int64

In [14]:
#7.Display number of times unique values appeared in each column
for col in df.columns:
    print(df[col].value_counts())

TEAM
North Carolina    12
Wisconsin         12
Michigan          12
Texas Tech        12
Gonzaga           12
                  ..
Louisiana          1
IU Indy            1
Mercyhurst         1
Detroit Mercy      1
West Georgia       1
Name: count, Length: 380, dtype: int64
CONF
ACC     180
A10     172
SEC     170
B10     168
CUSA    156
SB      145
MAC     144
Slnd    142
OVC     138
BSky    134
MAAC    133
P12     132
CAA     131
MEAC    131
B12     130
BE      130
MWC     130
BSth    129
SWAC    128
Amer    127
MVC     126
Horz    124
SC      123
WCC     119
ASun    119
BW      119
NEC     119
Pat     118
WAC     115
AE      110
Sum     107
Ivy      88
ind       6
GWC       5
Ind       1
Name: count, dtype: int64
G
31    630
32    616
30    530
33    493
29    412
34    309
28    244
35    224
27    137
36    128
37     79
26     79
25     57
24     40
22     39
23     34
38     31
20     27
21     24
18     24
19     23
39     17
40     12
17     12
15     11
16      6
14      4
9       2
13      2
5       1
10      1
12      1
Name: count, dtype: int64
W
14    264
16    244
20    236
15    235
17    231
12    225
11    220
13    212
18    211
19    205
22    183
21    178
9     173
10    172
23    157
7     129
8     128
24    121
25    101
6      93
26     91
27     81
5      67
4      53
28     51
29     39
30     27
31     26
3      26
32     16
2      15
33     10
1       8
35      7
36      4
34      4
0       4
37      1
38      1
Name: count, dtype: int64
ADJOE
101.3    34
107.9    33
104.7    32
101.1    31
99.9     31
         ..
124.8     1
124.9     1
125.6     1
88.0      1
83.1      1
Name: count, Length: 401, dtype: int64
ADJDE
102.5    36
104.2    36
106.4    36
103.8    32
107.5    32
         ..
121.2     1
119.0     1
117.6     1
121.8     1
125.3     1
Name: count, Length: 347, dtype: int64
BARTHAG
0.3181    5
0.5851    4
0.3345    4
0.2943    4
0.2684    4
         ..
0.0705    1
0.0688    1
0.0563    1
0.0556    1
0.0088    1
Name: count, Length: 3398, dtype: int64
EFG_O
49.4    65
51.3    65
49.9    64
50.6    64
51.2    63
        ..
61.0     1
41.4     1
59.2     1
59.9     1
57.2     1
Name: count, Length: 189, dtype: int64
EFG_D
49.9    73
49.6    70
51.2    69
51.0    69
51.4    64
        ..
41.5     1
57.3     1
60.1     1
41.3     1
58.1     1
Name: count, Length: 170, dtype: int64
TOR
18.2    95
18.7    92
18.3    90
18.5    88
18.1    87
        ..
26.8     1
25.7     1
27.1     1
24.4     1
12.0     1
Name: count, Length: 136, dtype: int64
TORD
18.5    88
18.2    86
18.0    83
17.6    81
18.6    80
        ..
11.6     1
11.4     1
11.1     1
12.9     1
10.5     1
Name: count, Length: 150, dtype: int64
ORB
29.4    47
31.8    47
27.0    47
31.7    46
29.0    46
        ..
17.3     1
14.4     1
17.0     1
39.9     1
18.4     1
Name: count, Length: 238, dtype: int64
DRB
28.6    69
30.5    68
29.4    63
31.2    62
28.5    61
        ..
21.1     1
21.6     1
18.7     1
21.8     1
20.2     1
Name: count, Length: 188, dtype: int64
FTR
34.6    42
33.0    40
31.6    39
30.4    38
34.3    37
        ..
21.0     1
23.5     1
50.0     1
45.2     1
22.2     1
Name: count, Length: 299, dtype: int64
FTRD
33.5    47
35.7    40
33.9    40
33.4    37
30.0    36
        ..
16.2     1
17.2     1
23.2     1
18.9     1
49.8     1
Name: count, Length: 339, dtype: int64
2P_O
48.8    63
49.2    60
48.3    59
49.8    58
48.4    56
        ..
62.0     1
59.7     1
58.1     1
59.9     1
61.1     1
Name: count, Length: 213, dtype: int64
2P_D
50.0    70
49.1    65
51.7    57
49.0    55
50.6    55
        ..
59.1     1
60.4     1
40.8     1
59.0     1
58.8     1
Name: count, Length: 195, dtype: int64
3P_O
35.6    75
34.6    74
32.6    73
34.1    72
35.1    68
        ..
25.1     1
43.7     1
26.6     1
24.7     1
27.0     1
Name: count, Length: 167, dtype: int64
3P_D
33.7    86
33.3    84
34.1    81
33.8    80
34.2    77
        ..
28.2     1
26.9     1
26.6     1
26.5     1
28.0     1
Name: count, Length: 147, dtype: int64
ADJ_T
66.4    71
67.2    70
67.1    67
68.5    65
67.5    62
        ..
58.4     1
58.5     1
76.7     1
76.0     1
77.1     1
Name: count, Length: 188, dtype: int64
WAB
-11.60    34
-11.70    31
-8.80     31
-12.60    30
-6.20     30
          ..
-0.48      1
-0.16      1
 0.13      1
 0.12      1
-21.50     1
Name: count, Length: 364, dtype: int64
POSTSEASON
R64          384
R32          192
S16           96
E8            48
R68           48
F4            24
2ND           12
Champions     12
Name: count, dtype: int64
SEED
16.0    72
11.0    68
10.0    50
12.0    50
3.0     49
13.0    49
1.0     48
8.0     48
2.0     48
7.0     48
6.0     48
5.0     48
14.0    48
15.0    48
4.0     47
9.0     47
Name: count, dtype: int64
YEAR
2025    364
2023    363
2024    362
2022    358
2019    353
2016    351
2015    351
2018    351
2017    351
2014    351
2013    347
2021    347
Name: count, dtype: int64

In [ ]:
#8.displays info about dataset 
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4249 entries, 0 to 4248
Data columns (total 24 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   TEAM        4249 non-null   str
 1   CONF        4249 non-null   str
 2   G           4249 non-null   int64
 3   W           4249 non-null   int64
 4   ADJOE       4249 non-null   float64
 5   ADJDE       4249 non-null   float64
 6   BARTHAG     4249 non-null   float64
 7   EFG_O       4249 non-null   float64
 8   EFG_D       4249 non-null   float64
 9   TOR         4249 non-null   float64
 10  TORD        4249 non-null   float64
 11  ORB         4249 non-null   float64
 12  DRB         4249 non-null   float64
 13  FTR         4249 non-null   float64
 14  FTRD        4249 non-null   float64
 15  2P_O        4249 non-null   float64
 16  2P_D        4249 non-null   float64
 17  3P_O        4249 non-null   float64
 18  3P_D        4249 non-null   float64
 19  ADJ_T       4249 non-null   float64
 20  WAB         4249 non-null   float64
 21  POSTSEASON  816 non-null    str
 22  SEED        816 non-null    float64
 23  YEAR        4249 non-null   int64
dtypes: float64(18), int64(3), str(3)
memory usage: 856.1 KB

In [ ]:
#10.gives statistical info about dataset
df.describe()

,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,TORD,ORB,...,FTR,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,SEED,YEAR
count,4249.000000,4249.000000,4249.000000,4249.000000,4249.000000,4249.000000,4249.000000,4249.000000,4249.000000,4249.000000,...,4249.000000,4249.000000,4249.000000,4249.000000,4249.000000,4249.000000,4249.000000,4249.000000,816.000000,4249.000000
mean,30.753589,16.177924,103.625865,103.627418,0.493439,50.006354,50.197670,18.441469,18.373923,29.302283,...,34.266486,34.523253,49.372747,49.534079,34.102189,34.279901,67.694493,-7.706672,8.797794,2018.968699
std,3.758512,6.497419,7.402858,6.563856,0.255445,3.080054,2.845484,2.160366,2.312224,4.201140,...,5.410060,6.266241,3.458268,3.311366,2.693363,2.387139,2.990581,6.870747,4.670970,3.892531
min,5.000000,0.000000,76.600000,84.000000,0.005000,39.200000,39.600000,11.900000,10.200000,14.400000,...,19.600000,16.200000,37.700000,37.700000,24.700000,26.100000,57.200000,-25.200000,1.000000,2013.000000
25%,29.000000,11.000000,98.600000,99.000000,0.281200,48.000000,48.300000,17.000000,16.800000,26.500000,...,30.500000,30.000000,47.000000,47.300000,32.300000,32.700000,65.700000,-12.800000,5.000000,2016.000000
50%,31.000000,16.000000,103.300000,103.800000,0.472500,50.000000,50.200000,18.300000,18.300000,29.400000,...,34.000000,33.900000,49.300000,49.500000,34.100000,34.200000,67.600000,-8.100000,9.000000,2019.000000
75%,33.000000,21.000000,108.300000,108.300000,0.715300,52.000000,52.100000,19.800000,19.800000,32.100000,...,37.700000,38.500000,51.600000,51.800000,35.900000,35.800000,69.600000,-3.100000,13.000000,2023.000000
max,40.000000,38.000000,130.600000,125.300000,0.984200,61.000000,60.100000,27.100000,28.500000,43.600000,...,58.600000,60.700000,64.000000,61.200000,44.100000,43.100000,83.400000,13.100000,16.000000,2025.000000

In [ ]:
#11.gives datatypes about all columns
df.dtypes

TEAM              str
CONF              str
G               int64
W               int64
ADJOE         float64
ADJDE         float64
BARTHAG       float64
EFG_O         float64
EFG_D         float64
TOR           float64
TORD          float64
ORB           float64
DRB           float64
FTR           float64
FTRD          float64
2P_O          float64
2P_D          float64
3P_O          float64
3P_D          float64
ADJ_T         float64
WAB           float64
POSTSEASON        str
SEED          float64
YEAR            int64
dtype: object

In [ ]:
#12.displays random row
df.sample()

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,YEAR
1295,Nicholls St.,Slnd,28,21,101.8,103.8,0.4465,51.9,50.2,20.4,...,45.2,51.6,49.7,34.8,34.1,75.2,-6.3,NaN,NaN,2018

In [27]:
#13.displays random n rows
df.sample(3)

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,YEAR
1259,Nicholls St.,Slnd,26,7,89.6,105.5,0.1321,47.8,50.0,25.0,...,50.7,48.4,48.3,31.2,35.7,66.8,-13.9,NaN,NaN,2015
1220,Arkansas,SEC,32,16,109.5,99.0,0.7602,49.7,49.8,15.3,...,42.9,46.1,47.7,39.7,35.9,71.0,-4.6,NaN,NaN,2016
692,Quinnipiac,MAAC,30,9,91.5,102.3,0.2167,42.8,46.5,21.7,...,40.1,38.3,46.5,34.1,31.0,69.6,-16.7,NaN,NaN,2016

In [ ]:
#14.counts non-null values
df.count()

TEAM          4249
CONF          4249
G             4249
W             4249
ADJOE         4249
ADJDE         4249
BARTHAG       4249
EFG_O         4249
EFG_D         4249
TOR           4249
TORD          4249
ORB           4249
DRB           4249
FTR           4249
FTRD          4249
2P_O          4249
2P_D          4249
3P_O          4249
3P_D          4249
ADJ_T         4249
WAB           4249
POSTSEASON     816
SEED           816
YEAR          4249
dtype: int64

In [ ]:
#15.counts min value amongst numerics
df.min(numeric_only=True)

G             5.000
W             0.000
ADJOE        76.600
ADJDE        84.000
BARTHAG       0.005
EFG_O        39.200
EFG_D        39.600
TOR          11.900
TORD         10.200
ORB          14.400
DRB          18.400
FTR          19.600
FTRD         16.200
2P_O         37.700
2P_D         37.700
3P_O         24.700
3P_D         26.100
ADJ_T        57.200
WAB         -25.200
SEED          1.000
YEAR       2013.000
dtype: float64

In [32]:
#16.gives mean of numeric values
df.mean(numeric_only=True)

G            30.753589
W            16.177924
ADJOE       103.625865
ADJDE       103.627418
BARTHAG       0.493439
EFG_O        50.006354
EFG_D        50.197670
TOR          18.441469
TORD         18.373923
ORB          29.302283
DRB          29.508096
FTR          34.266486
FTRD         34.523253
2P_O         49.372747
2P_D         49.534079
3P_O         34.102189
3P_D         34.279901
ADJ_T        67.694493
WAB          -7.706672
SEED          8.797794
YEAR       2018.968699
dtype: float64

In [33]:
#17.calculates sum of numerical columns
df.sum(numeric_only=True)

G          1.306720e+05
W          6.874000e+04
ADJOE      4.403063e+05
ADJDE      4.403129e+05
BARTHAG    2.096624e+03
EFG_O      2.124770e+05
EFG_D      2.132899e+05
TOR        7.835780e+04
TORD       7.807080e+04
ORB        1.245054e+05
DRB        1.253799e+05
FTR        1.455983e+05
FTRD       1.466893e+05
2P_O       2.097848e+05
2P_D       2.104703e+05
3P_O       1.449002e+05
3P_D       1.456553e+05
ADJ_T      2.876339e+05
WAB       -3.274565e+04
SEED       7.179000e+03
YEAR       8.578598e+06
dtype: float64